	DROP SEQUENCE myseq2;
2022-08-01 19:23:28.775 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.775 UTC [116199] STATEMENT:  
	-- Now OK:
	DROP SEQUENCE myseq2;
2022-08-01 19:23:28.775 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.775 UTC [116199] STATEMENT:    -- error, not a sequence
	
	CREATE SEQUENCE sequence_test2 START WITH 32;
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:  
	SELECT nextval('sequence_test2');
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:    -- cycled
	
	ALTER SEQUENCE sequence_test2 RESTART WITH 24
	  NO CYCLE;
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:  
	SELECT nextval('sequence_test2');
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:  
	SELECT nextval('sequence_test2');
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 19
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:    -- error
	SELECT setval('sequence_test2', 5);
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 77
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:    -- not read from, to test is_called
	
	
	-- Information schema
	SELECT * FROM information_schema.sequences
	  WHERE sequence_name ~ ANY(ARRAY['sequence_test', 'serialtest'])
	  ORDER BY sequence_name ASC;
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:  
	
	-- Test lastval()
	CREATE SEQUENCE seq;
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:  
	SELECT nextval('seq');
2022-08-01 19:23:28.776 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.776 UTC [116199] STATEMENT:  
	SELECT lastval();
2022-08-01 19:23:28.777 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.777 UTC [116199] STATEMENT:  
	SELECT lastval();
2022-08-01 19:23:28.777 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 9
2022-08-01 19:23:28.777 UTC [116199] STATEMENT:  
	SELECT nextval('sequence_test_temp1');
2022-08-01 19:23:28.777 UTC [116199] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-01 19:23:28.777 UTC [116199] STATEMENT:    -- ok
	SELECT nextval('sequence_test2');
2022-08-01 19:23:28.777 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.777 UTC [116199] STATEMENT:  
	CREATE SEQUENCE seq3;
2022-08-01 19:23:28.777 UTC [116199] WARNING:  there is no transaction in progress
2022-08-01 19:23:28.777 UTC [116199] WARNING:  SET LOCAL can only be used in transaction blocks
2022-08-01 19:23:28.777 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.777 UTC [116199] STATEMENT:  
	SET LOCAL SESSION AUTHORIZATION regress_seq_user;
2022-08-01 19:23:28.777 UTC [116199] WARNING:  SET LOCAL can only be used in transaction blocks
2022-08-01 19:23:28.777 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.777 UTC [116199] STATEMENT:  
	SET LOCAL SESSION AUTHORIZATION regress_seq_user;
2022-08-01 19:23:28.777 UTC [116199] WARNING:  SET LOCAL can only be used in transaction blocks
2022-08-01 19:23:28.778 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  
	SET LOCAL SESSION AUTHORIZATION regress_seq_user;
2022-08-01 19:23:28.778 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  
	CREATE SEQUENCE seq3;
2022-08-01 19:23:28.778 UTC [116199] WARNING:  there is no transaction in progress
2022-08-01 19:23:28.778 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  
	CREATE SEQUENCE seq3;
2022-08-01 19:23:28.778 UTC [116199] ERROR:  savepoint "save" does not exist
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  
	ROLLBACK TO save;
2022-08-01 19:23:28.778 UTC [116199] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  
	
	-- Sequences should get wiped out as well:
	DROP TABLE base_fn_out, int42_out;
2022-08-01 19:23:28.778 UTC [116199] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  
	
	DROP USER regress_seq_user;
2022-08-01 19:23:28.778 UTC [116199] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-01 19:23:28.778 UTC [116199] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 19:23:28.778 UTC [116199] STATEMENT:  DISCARD ALL;
2022-08-01 19:23:28.779 UTC [116199] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-01 19:23:28.779 UTC [116199] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-01 19:23:28.779 UTC [116199] ERROR:  schema "public" already exists
2022-08-01 19:23:28.779 UTC [116199] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-01 19:23:32.545 UTC [127921] PANIC:  could not open critical system index 2662
2022-08-01 19:23:32.548 UTC [107189] LOG:  server process (PID 127921) was terminated by signal 6: Aborted
2022-08-01 19:23:32.548 UTC [107189] LOG:  terminating any other active server processes
2022-08-01 19:23:32.580 UTC [107189] LOG:  all server processes terminated; reinitializing
2022-08-01 19:23:32.602 UTC [127922] LOG:  database system was interrupted; last known up at 2022-08-01 19:21:43 UTC
2022-08-01 19:23:32.651 UTC [127922] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-01 19:23:32.654 UTC [127922] LOG:  redo starts at 0/82A6B88
2022-08-01 19:23:33.111 UTC [127929] FATAL:  the database system is in recovery mode
2022-08-01 19:23:33.113 UTC [127932] FATAL:  the database system is in recovery mode
2022-08-01 19:23:33.116 UTC [127933] FATAL:  the database system is in recovery mode
2022-08-01 19:23:33.122 UTC [107189] LOG:  received smart shutdown request
2022-08-01 19:23:33.127 UTC [107189] LOG:  abnormal database system shutdown
